restore:
   build : couchdbdumps 
   links:
      - couchdb
      - learningregistry 
   volumes:
      - ./couchdbdumps:/tmp/couchdbdumps
   command: "/bin/sh -c 'dockerize -wait http://couchdb:5984 && cd /tmp/couchdbdumps && ./restoredb.sh && dockerize -wait http://learningregistry && ./uploadresources.sh'"
learningregistry:
  build: .
  links:
    - couchdb
  ports:
    - "8002:80"
couchdb:
  build: couch 
  expose:
   - "5984" 
